[package]
name = "hook-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-core = "0.58.0"

[dependencies.windows]
git = "https://github.com/microsoft/windows-rs"
features = [
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
]